In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from google.colab import files
uploaded=files.upload()

Saving bank-full.csv to bank-full.csv

In [5]:
df=pd.read_csv('/content/bank-full.csv')

In [6]:
df.head()

  age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0  58;"management";"married";"tertiary";"no";2143...
1  44;"technician";"single";"secondary";"no";29;"...
2  33;"entrepreneur";"married";"secondary";"no";2...
3  47;"blue-collar";"married";"unknown";"no";1506...
4  33;"unknown";"single";"unknown";"no";1;"no";"n...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 1 columns):
 #   Column                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                --------------  -----
 0   age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"  45211 non-null  object
dtypes: object(1)
memory usage: 353.3+ KB

In [8]:
df.describe()

       age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
count                                               45211
unique                                              45211
top     37;"entrepreneur";"married";"secondary";"no";2...
freq                                                    1

In [9]:
df.isnull().sum()

age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"    0
dtype: int64

In [10]:
df.shape

(45211, 1)

In [13]:
import pandas as pd

df = pd.read_csv("bank-full.csv", sep=";")

In [14]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [15]:
df = df.drop("duration", axis=1)

In [16]:
# Feature Engineering

df["Age_Group"] = pd.cut(
    df["age"],
    bins=[0, 30, 45, 60, 100],
    labels=["Young", "Adult", "Middle_Aged", "Senior"]
)

df["Balance_Per_Campaign"] = df["balance"] / (df["campaign"] + 1)

df["Contacted_Before"] = (df["previous"] > 0).astype(int)

df["Has_Debt"] = (
    (df["housing"] == "yes") |
    (df["loan"] == "yes")
).astype(int)

print("New Features Added Successfully!")

New Features Added Successfully!

In [17]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include="object").columns:
    df[col] = le.fit_transform(df[col])


for col in df.select_dtypes(include="category").columns:
    df[col] = le.fit_transform(df[col].astype(str))

In [18]:
from sklearn.model_selection import train_test_split

X = df.drop("y", axis=1)
y = df["y"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (36168, 19)
Testing Data Shape: (9043, 19)

In [19]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(
    criterion="gini",
    max_depth=8,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

dt.fit(X_train, y_train)

print("Decision Tree Model Trained Successfully!")

Decision Tree Model Trained Successfully!

In [20]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = dt.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Decision Tree Accuracy:", round(accuracy * 100, 2), "%")

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Decision Tree Accuracy: 89.01 %

Classification Report:

              precision    recall  f1-score   support

           0       0.90      0.98      0.94      7985
           1       0.59      0.20      0.30      1058

    accuracy                           0.89      9043
   macro avg       0.75      0.59      0.62      9043
weighted avg       0.87      0.89      0.87      9043


Confusion Matrix:

[[7838  147]
 [ 847  211]]

In [21]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(
    criterion="gini",
    random_state=42
)

In [22]:
!pip install chefboost

Collecting chefboost
  Downloading chefboost-0.0.19-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pandas>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from chefboost) (2.2.2)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from chefboost) (2.0.2)
Requirement already satisfied: tqdm>=4.30.0 in /usr/local/lib/python3.12/dist-packages (from chefboost) (4.67.3)
Requirement already satisfied: psutil>=5.4.3 in /usr/local/lib/python3.12/dist-packages (from chefboost) (5.9.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.22.0->chefboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.22.0->chefboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.22.0->chefboost) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.22.0->chefboost) (1.17.0)
Downloading chefboost-0.0.19-py3-none-any.whl (32 kB)
Installing collected packages: chefboost
Successfully installed chefboost-0.0.19

In [23]:
from chefboost import Chefboost as chef

df_id3 = df.copy()
df_id3.rename(columns={"y":"Decision"}, inplace=True)

df_id3["Decision"] = df_id3["Decision"].astype(str)

config = {"algorithm":"ID3"}

model = chef.fit(df_id3, config=config)

26-06-29 16:22:14 - ID3 tree is going to be built...
26-06-29 16:22:51 - -------------------------
26-06-29 16:22:51 - finished in 36.593273401260376 seconds
26-06-29 16:22:57 - -------------------------
26-06-29 16:22:57 - Evaluate train set
26-06-29 16:22:57 - -------------------------
26-06-29 16:22:57 - Accuracy: 89.31012364247638% on 45211 instances
26-06-29 16:22:57 - Labels: ['0' '1']
26-06-29 16:22:57 - Confusion matrix: [[39616, 4527], [306, 762]]
26-06-29 16:22:57 - Precision: 89.7447%, Recall: 99.2335%, F1: 94.2509%

In [25]:
from sklearn.tree import DecisionTreeClassifier

cart = DecisionTreeClassifier(
    criterion="gini",
    random_state=42
)

cart.fit(X_train, y_train)

y_pred = cart.predict(X_test)

from sklearn.metrics import accuracy_score
print("CART Accuracy:", accuracy_score(y_test, y_pred))

CART Accuracy: 0.8247263076412695

In [26]:
config = {"algorithm":"C4.5"}

model = chef.fit(df_id3, config=config)

26-06-29 16:24:25 - C4.5 tree is going to be built...
26-06-29 16:24:49 - -------------------------
26-06-29 16:24:49 - finished in 23.995290517807007 seconds
26-06-29 16:24:54 - -------------------------
26-06-29 16:24:54 - Evaluate train set
26-06-29 16:24:54 - -------------------------
26-06-29 16:24:54 - Accuracy: 89.02037114861427% on 45211 instances
26-06-29 16:24:54 - Labels: ['0' '1']
26-06-29 16:24:54 - Confusion matrix: [[39456, 4498], [466, 791]]
26-06-29 16:24:54 - Precision: 89.7666%, Recall: 98.8327%, F1: 94.0817%